### ISSUE TITLE
Display Code of Conduct on website

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/oscafrica.org-v1#26]
**Is your feature request related to a problem? Please describe.**
Code of conduct not available on the website

**Describe the solution you'd like**
I suggest we make the COC available on the website so as to allow new members know what's expected of them before they join.
The link to the COC should be added to the membership form, stating that you read the COC before you SignUp.

**Describe alternatives you've considered**
I could convert the COC markdown file to a simple website.

**Comment by samswag** [comment]
@BolajiAyodeji Please read first before raising an issue. They are totally different

**Comment by samswag** [comment]
> **Is your feature request related to a problem? Please describe.**
> Code of conduct not available on the website
> 
> **Describe the solution you'd like**
> I suggest we make the COC available on the website so as to allow new members know what's expected of them before they join.
> The link to the COC should be added to the membership form, stating that you read the COC before you SignUp.
> 
> **Describe alternatives you've considered**
> I could convert the COC markdown file to a simple website.

<img width="583" alt="screenshot 2018-11-19 at 4 03 16 pm" src="https://user-images.githubusercontent.com/6048601/48715167-aebe2c80-ec14-11e8-9819-7a6c90ba926b.png">
Again you need to check before opening an issue

**Comment by BolajiAyodeji** [comment]
I mean, directly on the site, not a bit link.
We could have it on the website.

**Comment by BolajiAyodeji** [comment]
Alright!
Although it would much more better as Inclusive communities need to allow their users to read the COC before hand.
Besides the link on the Form leads to 404, If that should be the only place it'd appear, that should be fixed and at least should not lead to GitHub markdown read as not all users would view with a PC, GitHub on mobile has differences.

**Comment by yomaokobiah** [comment]
@BolajiAyodeji on the website oscafrica.org there is OSCA Documentation which leads to the document repo and the code of conduct is there, very visible.

**Comment by BolajiAyodeji** [comment]
@Yomdroid OSCA Documentation is different from Code of Conduct even though I understand that its in it.
I hope you understand why I'm saying this, 100% inclusion.
Let users see it clearly that they're expected to read the COC before joining.
OSCA Documentation could mean resources to help them get started with OpenSource.

Lastly, leading them back to a GitHub repo is not cool, GitHub on Mobile is not really cool as it is on Desktop so those witout PS's would not have a nice treat.
I'm just saying all this just so we're inclusive enough.

**Comment by samswag** [comment]
I am going to close this issue because;
1. These documents are subject to change. Github is the right place to host documents since we don't have a wiki yet.

2. I don't want it on the website as per 1. Also, Github is better for docs than a website. 

3. The website has nothing to do with joining OSCA joining OSCA. Zulip is what we should be thinking of how we can add the code of conduct on the zulipchat platform.

OSCA documentations are going to be hosted to GitHub. 

Github works perfectly, I have seen organizations use it for docs.

<img width="1280" alt="screenshot 2018-11-24 at 11 38 00 am" src="https://user-images.githubusercontent.com/6048601/48967218-7ab08600-efdd-11e8-955c-87815bfc101e.png">
 Here is github on a old Samsun Galaxy S3 (2012) device. It looks great!! I also tested it on tecno phones and infinix just to be sure.

**Comment by samswag** [comment]
So can I close the issue now, because this isn't really an issue

**Comment by samswag** [comment]
<img width="1280" alt="screenshot 2018-11-24 at 11 55 26 am" src="https://user-images.githubusercontent.com/6048601/48967392-e98ede80-efdf-11e8-9d76-588d9e7692bf.png">

I think I have fix the issue

**Comment by BolajiAyodeji** [comment]
Yes!
That should work fine now.
